name: CI Backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Permitir execução do Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar e gerar artefato
        run: ./mvnw clean package
